### ISSUE TITLE
Trouble with popper.js

### ISSUE THREAD

**Issue by JanBessai** [webjars/bootstrap#71]
Version 4.0.0 depends on `popper.js`, which is loaded via RequireJS.
However, in the current version it cannot be found. I think the problem is, that webjars-locator [renames](https://github.com/webjars/webjars-locator/blob/7deefda582e06371d959503299ddc20c58e579e6/src/main/java/org/webjars/RequireJS.java#L410) `popper.js` to `popper-js`.

To reproduce, try
```
@{webJars.requireJs(routes.Assets.at("ui_init.js"))}
```
and
```
require(['bootstrap'], function(bootstrap) { alert("Ok"); });
```
which fails, where you get a browser debug console message about `js/popper.js`  not being found.
A viable alternative might be to use `bootstrap.bundle`, which includes `popper.js`.

**Comment by jamesward** [comment]
I think this might be due to something with the NPM WebJar RequireJS stuff.  So I want to try switching this over to a Classic WebJar.  I'm releasing `4.0.0-1` which I think should fix this.

**Comment by JanBessai** [comment]
This still doesn't fix the issue for me.
I've created a [test project](https://github.com/JanBessai/webjars-bootstrap-load-test) for it.

**Comment by JanBessai** [comment]
This doesn't seem to be fixed for me.
I've created a [demo project](https://github.com/JanBessai/webjars-bootstrap-load-test) to illustrate things (just run sbt test).

When you uncomment [the manual testing section](https://github.com/JanBessai/webjars-bootstrap-load-test/blob/master/src/test/scala/load/WebjarsBootstrapLoadTest.scala#L44) and try it in Firefox, there is an error about an export in popper and then it fails to load popper.js (as before), while the HtmlUnit selenium driver just throws
```
Error: Script error for "popper" http://requirejs.org/docs/errors.html#scripterror; 
Error: Load timeout for modules: bootstrap http://requirejs.org/docs/errors.html#timeout;
```

**Comment by jamesward** [comment]
Thanks for putting together the test app.  From that and some searching it looks like Popper is just not out-of-the-box compatible with requirejs:
http://blog.chasepeeler.com/2017/09/12/bootstrap-4-and-requirejs/
https://github.com/twbs/bootstrap/issues/23381
https://stackoverflow.com/questions/46004087/issue-loading-popperjs-and-bootstrap-via-requirejs-even-after-using-recommended

As far as I can tell, there isn't any way for us to fix this.  But let me know if you can think of a way.
